name : CiCheck
on: 
  pull_request:
    branches:
      - main
jobs:
  checkout-job:
    runs-on: ubuntu-22.04

    steps:
      - name: code checkout
      - uses: actions/checkout@v3

      - name: list files in repo
        run: |
          echo "Listing the files"
          ls -R
      
