name: Checkout and List Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout_and_list_files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: List files in the repository
      - name: List files
        run: |
          echo "Listing files in the repository"
          ls -R

      # Optional: You can also list the files on the server's file system (runner)
      - name: List files in the runner server
        run: |
          echo "Listing files in the runner server"
          ls -R /home/runner/work/$(basename $GITHUB_REPOSITORY)/$(basename $GITHUB_REPOSITORY)
